spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ro-el/Study/JPA/project/h2/jpashop;MVCC=TRUE
    user: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # hibernate ? ??? ?? ??? debug ?? -> ???? ?? sql ???